name: change_emitter
description: A flexible, highly composable alternative to ChangeNotifier for Flutter
version: 0.9.2

homepage: "https://github.com/jonaird/change_emitter"
repository: "https://github.com/jonaird/change_emitter"

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  async: ^2.4.2
  provider: ^4.3.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
