name: change_emitter
description: A flexible, highly composable alternative to ChangeNotifier for Flutter
version: 1.0.0-beta.2

homepage: "https://github.com/jonaird/change_emitter"
repository: "https://github.com/jonaird/change_emitter"

environment:
  sdk: ">=2.17.0-0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.5.0
  flutter:
    sdk: flutter

dev_dependencies:
  collection: ^1.15.0
  flutter_test:
    sdk: flutter


flutter:
